add really basic run impl to speed up iteration

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,13 +1,13 @@
 #!/bin/bash
 
 unset -v latest
-for file in tools/run/*.go; do
+for file in cmd/run/*.go; do
 	[[ $file -nt $latest ]] && latest=$file
 done
 
 if [ ! -f ./dist/run ] || [ $latest -nt ./dist/run ]; then
 	mkdir -p ./dist
-	go build -o ./dist/run tools/run/*.go || { echo 'failed to build run.go' ; exit 1; }
+	go build -o ./dist/run cmd/run/*.go || { echo 'failed to build run.go' ; exit 1; }
 fi
 
 ./dist/run "$@"
